nelmio_api_doc:
    documentation:
        info:
            title: Timekeeper API
            description: REST interface for Timekeeper 5
            version: 5.0.0
        servers:
            - url: http://localhost:8000/
              description: Local Development Server
            - url: https://api.technitivity.com/timekeeper/public/index.php/
              description: Production Server
    areas:
        path_patterns:
            # Accepts routes under /api except /api/doc
            - ^/login$
            - ^/api(?!/doc$)
