# Route to render the Swagger UI
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

# Route to expose the OpenAPI JSON specification (you already have app.swagger, but good to ensure consistency)
app.swagger_json:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

# Route to expose the OpenAPI JSON specification (you already have app.swagger, but good to ensure consistency)
app.swagger_yaml:
    path: /api/doc.yaml
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_yaml }