PUT {{baseUrl}}/api/v1/account/3?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json
X-API-KEY: {{tokenAccount1}}

{
  "username": "{{usernameAccount3}}",
  "password": "{{passwordAccount3}}",
  "email": "{{emailAccount3}}"
}
