PUT {{baseUrl}}/api/v1/account/3?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json
X-API-KEY: {{adminToken}}

{
  "username": "midnight",
  "password": "this is my third password",
  "email": "midnight@tmx.email",
  "admin": 0
}
