POST {{baseUrl}}/api/v1/account?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json
X-API-KEY: {{tokenAccount1}}

{
  "username": "{{usernameAccount4}}",
  "password": "{{passwordAccount4}}",
  "email": "{{emailAccount4}}"
}
