POST {{baseUrl}}/api/v1/account?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json
X-API-KEY: {{tokenAccount1}}

{
  "username": "{{usernameAccount2}}",
  "password": "{{passwordAccount2}}",
  "email": "{{emailAccount2}}",
  "admin": true
}
