PUT {{baseUrl}}/api/v1/account/2?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json
X-API-KEY: {{tokenAccount1}}

{
  "username": "{{$random.name.lastName}}{{$random.integer(1000,9999)}}",
  "password": "{{$random.alphanumeric(16)}}",
  "email": "{{$random.email}}"
}
