PUT {{baseUrl}}/api/v1/account/199?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json
X-API-KEY: {{adminToken}}

{
  "username": "jsmith-updated2",
  "email": "jsmith-updated2@example.com"
}
