POST {{baseUrl}}/api/v1/account?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json
X-API-KEY: {{adminToken}}

{
  "username": "jsmith",
  "password": "{{accountPassword}}",
  "email": "jsmith@example.com"
}
