POST {{baseUrl}}/api/v1/activity?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json
X-API-KEY: {{tokenAccount1}}

{
  "name": "{{$random.lorem.word}}",
  "description": "This is a new activity under folder 23",
  "folder": 23
}
