POST {{baseUrl}}/api/v1/profile?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json
X-API-KEY: {{adminToken}}

{
  "name": "{{$random.beer.name}}",
  "description": "This is my new profile created via profile-create.http",
  "account": 1
}
