PUT {{baseUrl}}/api/v1/profile/9?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json
X-API-KEY: {{adminToken}}

{
  "profile": "Music is Back",
  "description": "This is an updated description"
}
