POST {{baseUrl}}/api/v1/projectgroup?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json
X-API-KEY: {{adminToken}}

{
  "name": "{{$random.commerce.productName}}",
  "description": "This is a new project group under account 1",
  "account" : 1
}
