PUT {{baseUrl}}/api/v1/project/9?XDEBUG_SESSION_START=PHPSTORM
Content-Type: application/json
X-API-KEY: {{tokenAccount1}}

{
  "name": "{{$random.beer.name}}",
  "description": "This is an updated description"
}
